from dotenv import load_dotenv
load_dotenv() ## Load all the environment variables from the .env file


import streamlit as st
import os
import sqlite3

import google.generativeai as genai

## Configure our API Key
genai.configure(api_key=os.environ.get("GENAI_API_KEY"))

# Functio to load google gemini Model and provide SQL Query as reposnse
def get_gemini_response(question, prompt):
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content([prompt[0], question])
    return response.text

## Fcuntion to retrieve query from the sql Database
def read_sql_query(sql, db):
    conn = sqlite3.connect(db)
    cursor = conn.cursor()
    cursor.execute(sql)
    results = cursor.fetchall()
    conn.commit()
    conn.close()

    for result in results:
        print(result)

    return results

## Define your prompt for the model
prompt = """
    You are an expert in converting English questions to SQL query!
    The SQL database has the name students and has the following columns - namem class, section, MARKS. The data types of the columns are - name (VARCHAR), class (VARCHAR), section (VARCHAR), MARKS (INT).
    \n\n For example, 
        \n Example 1: How many entries of records are present and the SQL command will be something like this SELECT COUNT(*) FROM students; 
        \n Example 2: Tell me all the students studying in 11th class?, the SQL command will be something like this SELECT * FROM students WHERE class = '11th';
    also the sql code should not have ```in beginning or end and sql word in the output.```
"""


## Streamlit AOO
st.set_page_config(page_title="Text to SQL", page_icon=":guardsman:", layout="wide")
st.header("Text to SQL using Google Gemini Pro")

question = st.text_input("Enter your question here: ", key="input")

submit = st.button("Submit")


# If submit is clicked
if submit:
    reponse = get_gemini_response(question, prompt)
    print("SQL Query generated by Google Gemini Pro: ", reponse)
    data = read_sql_query(reponse, "student.db")
    st.subheader("The response is: ")
    for row in data:
        print(row)
        st.header(row)